ntrip-sources-file     =conf\ntripsources
trace-file             =
baselines-file         =conf\beselines
base-stations-info-file=
virtual-stations-file  =conf\vrsstations
rtk-conf-file          =
agent-user-file        =conf\agentuser
ntrip-record-file      =ntrip_record.dat
monitor-record-file    =monitor_record.dat
sourcetable-file       =conf\sourcetable
monitor-port           =7999

